// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftServeCinema.Infrastructure.Data;

#nullable disable

namespace SoftServeCinema.Infrastructure.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    partial class CinemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ActorEntityMovieEntity", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("ActorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("ActorEntityMovieEntity");

                    b.HasData(
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 1
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 1
                        },
                        new
                        {
                            ActorsId = 3,
                            MoviesId = 1
                        },
                        new
                        {
                            ActorsId = 4,
                            MoviesId = 1
                        },
                        new
                        {
                            ActorsId = 5,
                            MoviesId = 2
                        },
                        new
                        {
                            ActorsId = 6,
                            MoviesId = 2
                        },
                        new
                        {
                            ActorsId = 7,
                            MoviesId = 2
                        });
                });

            modelBuilder.Entity("DirectorEntityMovieEntity", b =>
                {
                    b.Property<int>("DirectorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("DirectorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("DirectorEntityMovieEntity");

                    b.HasData(
                        new
                        {
                            DirectorsId = 1,
                            MoviesId = 1
                        },
                        new
                        {
                            DirectorsId = 2,
                            MoviesId = 2
                        });
                });

            modelBuilder.Entity("GenreEntityMovieEntity", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("GenresId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("GenreEntityMovieEntity");

                    b.HasData(
                        new
                        {
                            GenresId = 1,
                            MoviesId = 1
                        },
                        new
                        {
                            GenresId = 2,
                            MoviesId = 1
                        },
                        new
                        {
                            GenresId = 3,
                            MoviesId = 1
                        },
                        new
                        {
                            GenresId = 2,
                            MoviesId = 2
                        },
                        new
                        {
                            GenresId = 4,
                            MoviesId = 2
                        });
                });

            modelBuilder.Entity("MovieEntityTagEntity", b =>
                {
                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("MoviesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("MovieEntityTagEntity");

                    b.HasData(
                        new
                        {
                            MoviesId = 1,
                            TagsId = 1
                        },
                        new
                        {
                            MoviesId = 2,
                            TagsId = 2
                        });
                });

            modelBuilder.Entity("SoftServeCinema.Core.Entities.ActorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кірстен Данст"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Джессі Племенс"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Кейлі Спені"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Соноя Мідзуно"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Раян Ґослінґ"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Емілі Блант"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Аарон Тейлор-Джонсон"
                        });
                });

            modelBuilder.Entity("SoftServeCinema.Core.Entities.DirectorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Алекс Ґарленд"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Девід Літч"
                        });
                });

            modelBuilder.Entity("SoftServeCinema.Core.Entities.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "епічний"
                        },
                        new
                        {
                            Id = 2,
                            Name = "екшн"
                        },
                        new
                        {
                            Id = 3,
                            Name = "антиутопія"
                        },
                        new
                        {
                            Id = 4,
                            Name = "комедія"
                        },
                        new
                        {
                            Id = 5,
                            Name = "трилер"
                        },
                        new
                        {
                            Id = 6,
                            Name = "жахи"
                        },
                        new
                        {
                            Id = 7,
                            Name = "пригоди"
                        },
                        new
                        {
                            Id = 8,
                            Name = "аніме"
                        },
                        new
                        {
                            Id = 9,
                            Name = "сімейний"
                        },
                        new
                        {
                            Id = 10,
                            Name = "драма"
                        },
                        new
                        {
                            Id = 11,
                            Name = "спорт"
                        },
                        new
                        {
                            Id = 12,
                            Name = "документальний"
                        });
                });

            modelBuilder.Entity("SoftServeCinema.Core.Entities.MovieEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<ushort>("Duration")
                        .HasColumnType("smallint unsigned");

                    b.Property<DateTime>("EndRentalDate")
                        .HasColumnType("datetime");

                    b.Property<ushort>("GraduationYear")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("StartRentalDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Події розгортаються у найближчому майбутньому. Сполученими штатами котиться нищівна та всеохоплююча громадянська війна. Почалося із бажання кількох південних штатів відділитися і тепер уся країна охоплена бойовими діями. Група журналістів, серед яких відома репортерка (Кірстен Данст), яка і раніше часто знімала збройні конфлікти, рухаються у напрямку Вашингтона. Стає очевидним, що керівництво країни перетворилося на диктатуру, а повстанські угрупування повсюдно чинять воєнні злочини.",
                            Duration = (ushort)108,
                            EndRentalDate = new DateTime(2024, 6, 14, 18, 4, 39, 829, DateTimeKind.Utc).AddTicks(8525),
                            GraduationYear = (ushort)2024,
                            ImagePath = "/movies/sw-vend.jpg",
                            StartRentalDate = new DateTime(2024, 5, 14, 18, 4, 39, 829, DateTimeKind.Utc).AddTicks(8520),
                            Title = "Повстання Штатів",
                            TrailerUrl = "https://www.youtube.com/embed/my8iHV3dpNI?si=88h7TyNtTLoGIupq"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Джоді Морено (Емілі Блант) знімає свій перший фільм у якості режисера. Вона дуже старається та хвилюється. Добре, що на знімальному майданчику завжди є кому її підбадьорити. Кольт (Раян Ґослінґ) – каскадер. Колись вони зустрічалися з Джоді, а нині просто працюють разом та підтримують одне одного. Кольт дублює актора, який грає головну роль. Якось цей актор безслідно зникає. Ніхто не може знайти його, а це означає, що Джоді не зможе дознімати свій дебютний проект і це зруйнує її кар’єру. Кольт дуже не хоче, щоб так сталося, тож погоджується стати на деякий час детективом та розшукати актора, який невідомо куди подівся.",
                            Duration = (ushort)126,
                            EndRentalDate = new DateTime(2024, 7, 4, 18, 4, 39, 829, DateTimeKind.Utc).AddTicks(8530),
                            GraduationYear = (ushort)2024,
                            ImagePath = "/movies/fall_guy-vend.jpg",
                            StartRentalDate = new DateTime(2024, 5, 20, 18, 4, 39, 829, DateTimeKind.Utc).AddTicks(8529),
                            Title = "Каскадер",
                            TrailerUrl = "https://www.youtube.com/embed/Xmi7ZsHL6Jg?si=v2CGyMa6CcT2KUUY"
                        });
                });

            modelBuilder.Entity("SoftServeCinema.Core.Entities.SessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasicPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("VipPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasicPrice = 200m,
                            MovieId = 1,
                            StartDate = new DateTime(2024, 5, 16, 18, 4, 39, 829, DateTimeKind.Utc).AddTicks(9084),
                            VipPrice = 350m
                        });
                });

            modelBuilder.Entity("SoftServeCinema.Core.Entities.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "18+"
                        },
                        new
                        {
                            Id = 2,
                            Name = "12+"
                        });
                });

            modelBuilder.Entity("SoftServeCinema.Core.Entities.TicketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime");

                    b.Property<short>("RowNumber")
                        .HasColumnType("smallint");

                    b.Property<short>("SeatNumber")
                        .HasColumnType("smallint");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)1,
                            SeatNumber = (short)1,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)1,
                            SeatNumber = (short)2,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 3,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)1,
                            SeatNumber = (short)3,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 4,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)1,
                            SeatNumber = (short)4,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 5,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)1,
                            SeatNumber = (short)5,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 6,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)1,
                            SeatNumber = (short)6,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 7,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)2,
                            SeatNumber = (short)1,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 8,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)2,
                            SeatNumber = (short)2,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 9,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)2,
                            SeatNumber = (short)3,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 10,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)2,
                            SeatNumber = (short)4,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 11,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)2,
                            SeatNumber = (short)5,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 12,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)2,
                            SeatNumber = (short)6,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 13,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)3,
                            SeatNumber = (short)1,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 14,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)3,
                            SeatNumber = (short)2,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 15,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)3,
                            SeatNumber = (short)3,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 16,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)3,
                            SeatNumber = (short)4,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 17,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)3,
                            SeatNumber = (short)5,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 18,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)3,
                            SeatNumber = (short)6,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 19,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)4,
                            SeatNumber = (short)1,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 20,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)4,
                            SeatNumber = (short)2,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 21,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)4,
                            SeatNumber = (short)3,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 22,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)4,
                            SeatNumber = (short)4,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 23,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)4,
                            SeatNumber = (short)5,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 24,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)4,
                            SeatNumber = (short)6,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 25,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)5,
                            SeatNumber = (short)1,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 26,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)5,
                            SeatNumber = (short)2,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 27,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)5,
                            SeatNumber = (short)3,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 28,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)5,
                            SeatNumber = (short)4,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 29,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)5,
                            SeatNumber = (short)5,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 30,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)5,
                            SeatNumber = (short)6,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 31,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)6,
                            SeatNumber = (short)1,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 32,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)6,
                            SeatNumber = (short)2,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 33,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)6,
                            SeatNumber = (short)3,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 34,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)6,
                            SeatNumber = (short)4,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 35,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)6,
                            SeatNumber = (short)5,
                            SessionId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 36,
                            ReservationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowNumber = (short)6,
                            SeatNumber = (short)6,
                            SessionId = 1,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("SoftServeCinema.Core.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("551b099b-91de-48ab-bb52-518a67f35e5b"),
                            Email = "romanmedvedev0201@gmail.com",
                            FirstName = "Roman",
                            LastName = "Koval",
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("ActorEntityMovieEntity", b =>
                {
                    b.HasOne("SoftServeCinema.Core.Entities.ActorEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftServeCinema.Core.Entities.MovieEntity", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectorEntityMovieEntity", b =>
                {
                    b.HasOne("SoftServeCinema.Core.Entities.DirectorEntity", null)
                        .WithMany()
                        .HasForeignKey("DirectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftServeCinema.Core.Entities.MovieEntity", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreEntityMovieEntity", b =>
                {
                    b.HasOne("SoftServeCinema.Core.Entities.GenreEntity", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftServeCinema.Core.Entities.MovieEntity", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieEntityTagEntity", b =>
                {
                    b.HasOne("SoftServeCinema.Core.Entities.MovieEntity", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftServeCinema.Core.Entities.TagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoftServeCinema.Core.Entities.SessionEntity", b =>
                {
                    b.HasOne("SoftServeCinema.Core.Entities.MovieEntity", "Movie")
                        .WithMany("Sessions")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("SoftServeCinema.Core.Entities.TicketEntity", b =>
                {
                    b.HasOne("SoftServeCinema.Core.Entities.SessionEntity", "Session")
                        .WithMany("Tickets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftServeCinema.Core.Entities.UserEntity", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftServeCinema.Core.Entities.MovieEntity", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SoftServeCinema.Core.Entities.SessionEntity", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SoftServeCinema.Core.Entities.UserEntity", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
